env:
  commonjs: true
  es2022: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
ignorePatterns:
  - node_modules/
  - dist/
rules: {}
